################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/bus_voltage_sensor.c \
E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/circle_limitation.c \
E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/digital_output.c \
E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/hall_speed_pos_fdbk.c \
E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/mcp.c \
E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/mcpa.c \
E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/motor_power_measurement.c \
E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/ntc_temperature_sensor.c \
E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/open_loop.c \
E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/pid_regulator.c \
E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/pqd_motor_power_measurement.c \
E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/pwm_common.c \
E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/F4xx/Src/r3_2_f4xx_pwm_curr_fdbk.c \
E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/r_divider_bus_voltage_sensor.c \
E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/ramp_ext_mngr.c \
E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/revup_ctrl.c \
E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/speed_pos_fdbk.c \
E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/speed_torq_ctrl.c \
E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/state_machine.c \
E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/virtual_speed_sensor.c 

OBJS += \
./Middlewares/MotorControl/bus_voltage_sensor.o \
./Middlewares/MotorControl/circle_limitation.o \
./Middlewares/MotorControl/digital_output.o \
./Middlewares/MotorControl/hall_speed_pos_fdbk.o \
./Middlewares/MotorControl/mcp.o \
./Middlewares/MotorControl/mcpa.o \
./Middlewares/MotorControl/motor_power_measurement.o \
./Middlewares/MotorControl/ntc_temperature_sensor.o \
./Middlewares/MotorControl/open_loop.o \
./Middlewares/MotorControl/pid_regulator.o \
./Middlewares/MotorControl/pqd_motor_power_measurement.o \
./Middlewares/MotorControl/pwm_common.o \
./Middlewares/MotorControl/r3_2_f4xx_pwm_curr_fdbk.o \
./Middlewares/MotorControl/r_divider_bus_voltage_sensor.o \
./Middlewares/MotorControl/ramp_ext_mngr.o \
./Middlewares/MotorControl/revup_ctrl.o \
./Middlewares/MotorControl/speed_pos_fdbk.o \
./Middlewares/MotorControl/speed_torq_ctrl.o \
./Middlewares/MotorControl/state_machine.o \
./Middlewares/MotorControl/virtual_speed_sensor.o 

C_DEPS += \
./Middlewares/MotorControl/bus_voltage_sensor.d \
./Middlewares/MotorControl/circle_limitation.d \
./Middlewares/MotorControl/digital_output.d \
./Middlewares/MotorControl/hall_speed_pos_fdbk.d \
./Middlewares/MotorControl/mcp.d \
./Middlewares/MotorControl/mcpa.d \
./Middlewares/MotorControl/motor_power_measurement.d \
./Middlewares/MotorControl/ntc_temperature_sensor.d \
./Middlewares/MotorControl/open_loop.d \
./Middlewares/MotorControl/pid_regulator.d \
./Middlewares/MotorControl/pqd_motor_power_measurement.d \
./Middlewares/MotorControl/pwm_common.d \
./Middlewares/MotorControl/r3_2_f4xx_pwm_curr_fdbk.d \
./Middlewares/MotorControl/r_divider_bus_voltage_sensor.d \
./Middlewares/MotorControl/ramp_ext_mngr.d \
./Middlewares/MotorControl/revup_ctrl.d \
./Middlewares/MotorControl/speed_pos_fdbk.d \
./Middlewares/MotorControl/speed_torq_ctrl.d \
./Middlewares/MotorControl/state_machine.d \
./Middlewares/MotorControl/virtual_speed_sensor.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/MotorControl/bus_voltage_sensor.o: E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/bus_voltage_sensor.c Middlewares/MotorControl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DSTM32F407xx -c -I../../Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/F4xx/Inc -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/circle_limitation.o: E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/circle_limitation.c Middlewares/MotorControl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DSTM32F407xx -c -I../../Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/F4xx/Inc -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/digital_output.o: E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/digital_output.c Middlewares/MotorControl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DSTM32F407xx -c -I../../Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/F4xx/Inc -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/hall_speed_pos_fdbk.o: E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/hall_speed_pos_fdbk.c Middlewares/MotorControl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DSTM32F407xx -c -I../../Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/F4xx/Inc -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/mcp.o: E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/mcp.c Middlewares/MotorControl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DSTM32F407xx -c -I../../Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/F4xx/Inc -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/mcpa.o: E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/mcpa.c Middlewares/MotorControl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DSTM32F407xx -c -I../../Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/F4xx/Inc -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/motor_power_measurement.o: E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/motor_power_measurement.c Middlewares/MotorControl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DSTM32F407xx -c -I../../Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/F4xx/Inc -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/ntc_temperature_sensor.o: E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/ntc_temperature_sensor.c Middlewares/MotorControl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DSTM32F407xx -c -I../../Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/F4xx/Inc -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/open_loop.o: E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/open_loop.c Middlewares/MotorControl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DSTM32F407xx -c -I../../Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/F4xx/Inc -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/pid_regulator.o: E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/pid_regulator.c Middlewares/MotorControl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DSTM32F407xx -c -I../../Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/F4xx/Inc -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/pqd_motor_power_measurement.o: E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/pqd_motor_power_measurement.c Middlewares/MotorControl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DSTM32F407xx -c -I../../Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/F4xx/Inc -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/pwm_common.o: E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/pwm_common.c Middlewares/MotorControl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DSTM32F407xx -c -I../../Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/F4xx/Inc -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/r3_2_f4xx_pwm_curr_fdbk.o: E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/F4xx/Src/r3_2_f4xx_pwm_curr_fdbk.c Middlewares/MotorControl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DSTM32F407xx -c -I../../Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/F4xx/Inc -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/r_divider_bus_voltage_sensor.o: E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/r_divider_bus_voltage_sensor.c Middlewares/MotorControl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DSTM32F407xx -c -I../../Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/F4xx/Inc -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/ramp_ext_mngr.o: E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/ramp_ext_mngr.c Middlewares/MotorControl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DSTM32F407xx -c -I../../Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/F4xx/Inc -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/revup_ctrl.o: E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/revup_ctrl.c Middlewares/MotorControl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DSTM32F407xx -c -I../../Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/F4xx/Inc -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/speed_pos_fdbk.o: E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/speed_pos_fdbk.c Middlewares/MotorControl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DSTM32F407xx -c -I../../Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/F4xx/Inc -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/speed_torq_ctrl.o: E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/speed_torq_ctrl.c Middlewares/MotorControl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DSTM32F407xx -c -I../../Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/F4xx/Inc -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/state_machine.o: E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/state_machine.c Middlewares/MotorControl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DSTM32F407xx -c -I../../Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/F4xx/Inc -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/MotorControl/virtual_speed_sensor.o: E:/app/julia/ebf_motor_tutorial_code_stm32f407_jiaoyang/improve_part2/BLDC_FOC_V5.Y.2_Hall_speed_control/BLDC_control/MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Src/virtual_speed_sensor.c Middlewares/MotorControl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DSTM32F407xx -c -I../../Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/Any/Inc -I../../MCSDK_v5.Y.2-Full/MotorControl/MCSDK/MCLib/F4xx/Inc -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-MotorControl

clean-Middlewares-2f-MotorControl:
	-$(RM) ./Middlewares/MotorControl/bus_voltage_sensor.d ./Middlewares/MotorControl/bus_voltage_sensor.o ./Middlewares/MotorControl/bus_voltage_sensor.su ./Middlewares/MotorControl/circle_limitation.d ./Middlewares/MotorControl/circle_limitation.o ./Middlewares/MotorControl/circle_limitation.su ./Middlewares/MotorControl/digital_output.d ./Middlewares/MotorControl/digital_output.o ./Middlewares/MotorControl/digital_output.su ./Middlewares/MotorControl/hall_speed_pos_fdbk.d ./Middlewares/MotorControl/hall_speed_pos_fdbk.o ./Middlewares/MotorControl/hall_speed_pos_fdbk.su ./Middlewares/MotorControl/mcp.d ./Middlewares/MotorControl/mcp.o ./Middlewares/MotorControl/mcp.su ./Middlewares/MotorControl/mcpa.d ./Middlewares/MotorControl/mcpa.o ./Middlewares/MotorControl/mcpa.su ./Middlewares/MotorControl/motor_power_measurement.d ./Middlewares/MotorControl/motor_power_measurement.o ./Middlewares/MotorControl/motor_power_measurement.su ./Middlewares/MotorControl/ntc_temperature_sensor.d ./Middlewares/MotorControl/ntc_temperature_sensor.o ./Middlewares/MotorControl/ntc_temperature_sensor.su ./Middlewares/MotorControl/open_loop.d ./Middlewares/MotorControl/open_loop.o ./Middlewares/MotorControl/open_loop.su ./Middlewares/MotorControl/pid_regulator.d ./Middlewares/MotorControl/pid_regulator.o ./Middlewares/MotorControl/pid_regulator.su ./Middlewares/MotorControl/pqd_motor_power_measurement.d ./Middlewares/MotorControl/pqd_motor_power_measurement.o ./Middlewares/MotorControl/pqd_motor_power_measurement.su ./Middlewares/MotorControl/pwm_common.d ./Middlewares/MotorControl/pwm_common.o ./Middlewares/MotorControl/pwm_common.su ./Middlewares/MotorControl/r3_2_f4xx_pwm_curr_fdbk.d ./Middlewares/MotorControl/r3_2_f4xx_pwm_curr_fdbk.o ./Middlewares/MotorControl/r3_2_f4xx_pwm_curr_fdbk.su ./Middlewares/MotorControl/r_divider_bus_voltage_sensor.d ./Middlewares/MotorControl/r_divider_bus_voltage_sensor.o ./Middlewares/MotorControl/r_divider_bus_voltage_sensor.su ./Middlewares/MotorControl/ramp_ext_mngr.d ./Middlewares/MotorControl/ramp_ext_mngr.o ./Middlewares/MotorControl/ramp_ext_mngr.su ./Middlewares/MotorControl/revup_ctrl.d ./Middlewares/MotorControl/revup_ctrl.o ./Middlewares/MotorControl/revup_ctrl.su ./Middlewares/MotorControl/speed_pos_fdbk.d ./Middlewares/MotorControl/speed_pos_fdbk.o ./Middlewares/MotorControl/speed_pos_fdbk.su ./Middlewares/MotorControl/speed_torq_ctrl.d ./Middlewares/MotorControl/speed_torq_ctrl.o ./Middlewares/MotorControl/speed_torq_ctrl.su ./Middlewares/MotorControl/state_machine.d ./Middlewares/MotorControl/state_machine.o ./Middlewares/MotorControl/state_machine.su ./Middlewares/MotorControl/virtual_speed_sensor.d ./Middlewares/MotorControl/virtual_speed_sensor.o ./Middlewares/MotorControl/virtual_speed_sensor.su

.PHONY: clean-Middlewares-2f-MotorControl

